dist: trusty
sudo: required
language: python
cache: pip
python:
 - 3.5
 - 3.6

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y beanstalkd
install: 
  - make install-test
  - pip install coveralls

script: 
  - make lint test
after_success:
  - coveralls
